version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - run:
          command: python3 -m pip install --upgrade pip
          name: Install Dependencies
      - run:
          command: pip3 install -r requirements-dev.txt
          name: Install Developer Dependencies
      - python/save-cache
      - run:
          command: python3 -m pytest tests
          name: Test

workflows:
  main:
    jobs:
      - build-and-test
